/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const LEVELS = [
  // 1: Classic
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B B . . . B B . . B B . . . B B . S",
    "S . B B . . . B B . . B B . . . B B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . S S . B B S S B B S S . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B B . . . W W . . B B . . . B B . S",
    "S . B B . . . W W . . B B . . . B B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B B . . . B B . . B B . . . B B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  // 2: The Maze
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . S . . . S . . . S . . . . . . S",
    "S . S . S . S . S . S . S . S S S S . S",
    "S . S . . . S . . . S . . . S . . . . S",
    "S . S S S S S S S S S S S . S . S S . S",
    "S . . . . . . . . . . . . . S . S . . S",
    "S S S S . S S S S S S S S S S . S . S S",
    "S . . . . S . . . . . . . . . . S . . S",
    "S . S S S S . S S S S S S S S S S S . S",
    "S . S . . . . S . . . . . . . . . . . S",
    "S . S . S S S S . S S S S S S S . S . S",
    "S . . . . . . . . . . . . . . . . S . S",
    "S . . . . . . . . . . . . . . . . S . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  // 3: River Cross
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B B B . . . . . . . . . B B B . . S",
    "S . B B B . . . . . . . . . B B B . . S",
    "S W W W W W W . . . . . W W W W W W . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S W W W W W W . . . . . W W W W W W . S",
    "S . B B B . . . . . . . . . B B B . . S",
    "S . B B B . . . . . . . . . B B B . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  // 4: The Fortress
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . S S S S S S S S S S S S S S S . . S",
    "S . S . . . . . . . . . . . . . S . . S",
    "S . S . B B B B B B B B B B B . S . . S",
    "S . S . B . . . . . . . . . B . S . . S",
    "S . S . B . . . . . . . . . B . S . . S",
    "S . S . B . . . S S S . . . B . S . . S",
    "S . S . B . . . . . . . . . B . S . . S",
    "S . S . B B B B B B B B B B B . S . . S",
    "S . S . . . . . . . . . . . . . S . . S",
    "S . S S S S S S S S S S S S S S S . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  // 5: Forest Ambush
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S U U U U U U U U U U U U U U U U U U S",
    "S U . . . . . . . . . . . . . . . . U S",
    "S U . B B . . . . . . . . . B B . . U S",
    "S U . B B . . . . . . . . . B B . . U S",
    "S U . . . . U U U U U U U . . . . . U S",
    "S U . . . . U . . . . . U . . . . . U S",
    "S U . . . . U . . . . . U . . . . . U S",
    "S U . . . . U U U U U U U . . . . . U S",
    "S U . B B . . . . . . . . . B B . . U S",
    "S U . B B . . . . . . . . . B B . . U S",
    "S U . . . . . . . . . . . . . . . . U S",
    "S U U U U U U U U U U U U U U U U U U S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  // 6: Crossfire
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . S . . . . . . . . . S",
    "S . . . . . . . . S . . . . . . . . . S",
    "S . . . . . . . . S . . . . . . . . . S",
    "S . . . . . . . . S . . . . . . . . . S",
    "S . . . . . . . . S . . . . . . . . . S",
    "S S S S S S S S . . . S S S S S S S S S",
    "S S S S S S S S . . . S S S S S S S S S",
    "S . . . . . . . . S . . . . . . . . . S",
    "S . . . . . . . . S . . . . . . . . . S",
    "S . . . . . . . . S . . . . . . . . . S",
    "S . . . . . . . . S . . . . . . . . . S",
    "S . . . . . . . . S . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  // 7: Islands
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B B . . W W . . B B . . W W . . . S",
    "S . B B . . W W . . B B . . W W . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . W W . . B B . . W W . . B B . . . S",
    "S . W W . . B B . . W W . . B B . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B B . . W W . . B B . . W W . . . S",
    "S . B B . . W W . . B B . . W W . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  // 8: The Labyrinth
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . S . . . . . . . . . S . . . S",
    "S . S S . S . S S S S S S S . S . S . S",
    "S . S . . . . . . . . . . . . . . S . S",
    "S . S . S S S S S S B B S S S S . S . S",
    "S . . . S . . . . . B B . . . . . . . S",
    "S S S . S . S S S . . . S S S . S S S S",
    "S . . . . . S . . . . . . . S . . . . S",
    "S . S S S S S . S S W S S . S S S S . S",
    "S . . . . . . . S W W W S . . . . . . S",
    "S . B B B B B . S S W S S . B B B B B S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  // 9-15: Procedural/Simple variations to complete count
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B B B B B B B B B B B B B B B B . S",
    "S . B . . . . . . . . . . . . . . B . S",
    "S . B . S S S S S S S S S S S S . B . S",
    "S . B . S . . . . . . . . . . S . B . S",
    "S . B . S . W W W W W W W . . S . B . S",
    "S . B . S . . . . . . . . . . S . B . S",
    "S . B . S S S S S S S S S S S S . B . S",
    "S . B . . . . . . . . . . . . . . B . S",
    "S . B B B B B B B B B B B B B B B B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B B . . . . . . . . . . . . B B . S",
    "S . . B B . . . . . . . . . . B B . . S",
    "S . . . B B . . . . . . . . B B . . . S",
    "S . . . . B B . . . . . . B B . . . . S",
    "S . . . . . B B . . . . B B . . . . . S",
    "S . . . . . . B B . . B B . . . . . . S",
    "S . . . . . B B . . . . B B . . . . . S",
    "S . . . . B B . . . . . . B B . . . . S",
    "S . . . B B . . . . . . . . B B . . . S",
    "S . . B B . . . . . . . . . . B B . . S",
    "S . B B . . . . . . . . . . . . B B . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B S B S B S B S B S B S B S B S . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . S B S B S B S B S B S B S B S B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B S B S B S B S B S B S B S B S . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . S B S B S B S B S B S B S B S B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B S B S B S B S B S B S B S B S . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B B B B . . . . . . . . B B B B . S",
    "S . B S S B . . . . . . . . B S S B . S",
    "S . B S S B . . . . . . . . B S S B . S",
    "S . B B B B . . S S S S . . B B B B . S",
    "S . . . . . . . S B B S . . . . . . . S",
    "S . . . . . . . S B B S . . . . . . . S",
    "S . B B B B . . S S S S . . B B B B . S",
    "S . B S S B . . . . . . . . B S S B . S",
    "S . B S S B . . . . . . . . B S S B . S",
    "S . B B B B . . . . . . . . B B B B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . U U . S S . U U . S S . U U . S S . S",
    "S . U U . S S . U U . S S . U U . S S . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . S S . U U . S S . U U . S S . U U . S",
    "S . S S . U U . S S . U U . S S . U U . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . U U . S S . U U . S S . U U . S S . S",
    "S . U U . S S . U U . S S . U U . S S . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B . B . B . B . B . B . B . B . B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B . S S S S S S S S S S S S S . B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B . S . . . . . . . . . . S . B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B . S S S S S S S S S S S S S . B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B . B . B . B . B . B . B . B . B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
  [
    "S S S S S S S S S S S S S S S S S S S S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B B B . W W W . B B B . W W W . B . S",
    "S . B . B . W . W . B . B . W . W . B . S",
    "S . B B B . W W W . B B B . W W W . B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B . B . W . W . B . B . W . W . B . S",
    "S . B B B . W W W . B B B . W W W . B . S",
    "S . B . B . W . W . B . B . W . W . B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . B B B . W W W . B B B . W W W . B . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S . . . . . . . . . . . . . . . . . . S",
    "S S S S S S S S S S S S S S S S S S S S",
  ],
];

// B: Brick, S: Steel, W: Water, U: Bush, .: Empty
